### ISSUE TITLE
Cannot use mmacells package

### ISSUE THREAD

**Issue by wtchan** [jkuczm/mmacells#17]
when compiling, the following error emerges:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "keys/property-unknown"
!
! The key property '.initial:n' is unknown.
!
! See the LaTeX3 documentation for further information.
!
! For immediate help type H <return>.
!...............................................
l.371 }
|'''''''''''''''''''''''''''''''''''''''''''''''
| This is a coding error.
|
| LaTeX has been asked to set the property '.initial:n' for key
| 'mmacells/verbatimenv': this property is not defined.
|...............................................

**Comment by jkuczm** [comment]
Could you provide a minimal `.tex` file that causes this error, together with `.log` file produced by compilation?

Without it, I'd guess that you're using outdated version of LaTeX3.
`.initial:n` property was introduced to `l3keys` package in  2012-06-02.

**Comment by wtchan** [comment]
% minimal .tex
\documentclass{article}
\usepackage{mmacells}
\begin{document}

\end{document}

% log file
This is pdfTeX, Version 3.1415926-2.4-1.40.13 (TeX Live 2012/Debian) (format=pdflatex 2015.4.19)  28 APR 2015 09:18
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**jack.tex
(./jack.tex
LaTeX2e <2011/06/27>
Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, et
hiopic, farsi, arabic, pinyin, croatian, bulgarian, ukrainian, russian, slovak,
 czech, danish, dutch, usenglishmax, ukenglish, finnish, french, basque, ngerma
n, german, swissgerman, ngerman-x-2012-05-30, german-x-2012-05-30, monogreek, g
reek, ibycus, ancientgreek, hungarian, bengali, tamil, hindi, telugu, gujarati,
 sanskrit, malayalam, kannada, assamese, marathi, oriya, panjabi, italian, lati
n, latvian, lithuanian, mongolian, mongolianlmc, nynorsk, bokmal, indonesian, e
speranto, coptic, welsh, irish, interlingua, serbian, serbianc, slovenian, friu
lan, romansh, estonian, romanian, armenian, uppersorbian, turkish, afrikaans, i
celandic, kurmanji, polish, portuguese, galician, catalan, spanish, swedish, uk
english, loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2007/10/19 v1.4h Standard LaTeX file (size option)
)
\c@part=\count79
\c@section=\count80
\c@subsection=\count81
\c@subsubsection=\count82
\c@paragraph=\count83
\c@subparagraph=\count84
\c@figure=\count85
\c@table=\count86
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
)
(/home/nxr/texmf/tex/latex/local/mmacells/mmacells.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3names.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3bootstrap.sty
Package: l3bootstrap 2011/12/29 v3110 L3 Experimental bootstrap code
)
Package: l3names 2012/03/04 v3494 L3 Experimental namespace for primitives
)
(/usr/share/texlive/texmf-dist/tex/latex/etex-pkg/etex.sty
Package: etex 1998/03/26 v2.0 eTeX basic definition package (PEB)
\et@xins=\count87
)
Package: expl3 2012/04/23 v3570 L3 Experimental code bundle wrapper

(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
Package: color 2005/11/14 v1.0j Standard LaTeX Color (DPC)

(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg
File: color.cfg 2007/01/18 v1.5 color configuration of teTeX/TeXLive
)
Package color Info: Driver file: pdftex.def on input line 130.

(/usr/share/texlive/texmf-dist/tex/latex/pdftex-def/pdftex.def
File: pdftex.def 2011/05/27 v0.06d Graphics/color for pdfTeX

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty
Package: infwarerr 2010/04/08 v1.3 Providing info/warning/error messages (HO)
)
(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty
Package: ltxcmds 2011/11/09 v1.22 LaTeX kernel commands for general use (HO)
)
\Gread@gobject=\count88
))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
Package: graphics 2009/02/05 v1.0o Standard LaTeX Graphics (DPC,SPQR)

(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty
Package: trig 1999/03/16 v1.09 sin cos tan (DPC)
)
(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg
File: graphics.cfg 2010/04/23 v1.9 graphics configuration of TeX Live
)
Package graphics Info: Driver file: pdftex.def on input line 91.
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3basics.sty
Package: l3basics 2012/03/04 v3491 L3 Experimental basic definitions
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3expan.sty
Package: l3expan 2012/02/26 v3460 L3 Experimental argument expansion
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3tl.sty
Package: l3tl 2012/03/04 v3490 L3 Experimental token lists
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3seq.sty
Package: l3seq 2012/03/04 v3490 L3 Experimental sequences and stacks
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3int.sty
Package: l3int 2012/03/04 v3490 L3 Experimental integers
\c_max_int=\count89
\l_tmpa_int=\count90
\l_tmpb_int=\count91
\l_tmpc_int=\count92
\g_tmpa_int=\count93
\g_tmpb_int=\count94
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3quark.sty
Package: l3quark 2012/02/12 v3384 L3 Experimental quarks
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3prg.sty
Package: l3prg 2012/03/04 v3490 L3 Experimental control structures
\g_prg_map_int=\count95
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3clist.sty
Package: l3clist 2012/03/04 v3490 L3 Experimental comma separated lists
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3token.sty
Package: l3token 2012/03/04 v3491 L3 Experimental token manipulation
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3prop.sty
Package: l3prop 2012/03/04 v3490 L3 Experimental property lists
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3msg.sty
Package: l3msg 2012/04/23 v3568 L3 Experimental messages
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3file.sty
Package: l3file 2012/03/09 v3520 L3 Experimental file and I/O operations
\l_iow_stream_int=\count96
\l_iow_line_length_int=\count97
\l_iow_target_length_int=\count98
\l_iow_current_line_int=\count99
\l_iow_current_word_int=\count100
\l_iow_current_indentation_int=\count101
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3skip.sty
Package: l3skip 2012/03/05 v3499 L3 Experimental dimensions and skips
\l_tmpa_dim=\dimen103
\l_tmpb_dim=\dimen104
\l_tmpc_dim=\dimen105
\g_tmpa_dim=\dimen106
\g_tmpb_dim=\dimen107
\l_tmpa_skip=\skip43
\l_tmpb_skip=\skip44
\l_tmpc_skip=\skip45
\g_tmpa_skip=\skip46
\g_tmpb_skip=\skip47
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3keys.sty
Package: l3keys 2012/03/03 v3487 L3 Experimental key-value interfaces
\g_keyval_level_int=\count102
\l_keys_choice_int=\count103
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3fp.sty
Package: l3fp 2012/03/04 v3490 L3 Experimental floating-point operations
\c_one_million=\count104
\c_one_hundred_million=\count105
\c_five_hundred_million=\count106
\c_one_thousand_million=\count107
\c_fp_pi_by_four_decimal_int=\count108
\c_fp_pi_by_four_extended_int=\count109
\c_fp_pi_decimal_int=\count110
\c_fp_pi_extended_int=\count111
\c_fp_two_pi_decimal_int=\count112
\c_fp_two_pi_extended_int=\count113
\l_fp_count_int=\count114
\l_fp_div_offset_int=\count115
\l_fp_exp_integer_int=\count116
\l_fp_exp_decimal_int=\count117
\l_fp_exp_extended_int=\count118
\l_fp_exp_exponent_int=\count119
\l_fp_input_a_sign_int=\count120
\l_fp_input_a_integer_int=\count121
\l_fp_input_a_decimal_int=\count122
\l_fp_input_a_exponent_int=\count123
\l_fp_input_b_sign_int=\count124
\l_fp_input_b_integer_int=\count125
\l_fp_input_b_decimal_int=\count126
\l_fp_input_b_exponent_int=\count127
\l_fp_input_a_extended_int=\count128
\l_fp_input_b_extended_int=\count129
\l_fp_mul_a_i_int=\count130
\l_fp_mul_a_ii_int=\count131
\l_fp_mul_a_iii_int=\count132
\l_fp_mul_a_iv_int=\count133
\l_fp_mul_a_v_int=\count134
\l_fp_mul_a_vi_int=\count135
\l_fp_mul_b_i_int=\count136
\l_fp_mul_b_ii_int=\count137
\l_fp_mul_b_iii_int=\count138
\l_fp_mul_b_iv_int=\count139
\l_fp_mul_b_v_int=\count140
\l_fp_mul_b_vi_int=\count141
\l_fp_mul_output_int=\count142
\l_fp_output_sign_int=\count143
\l_fp_output_integer_int=\count144
\l_fp_output_decimal_int=\count145
\l_fp_output_exponent_int=\count146
\l_fp_output_extended_int=\count147
\l_fp_round_position_int=\count148
\l_fp_round_target_int=\count149
\l_fp_split_sign_int=\count150
\l_fp_internal_int=\count151
\l_fp_trig_octant_int=\count152
\l_fp_trig_sign_int=\count153
\l_fp_trig_decimal_int=\count154
\l_fp_trig_extended_int=\count155
\l_fp_internal_dim=\dimen108
\l_fp_internal_skip=\skip48
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3box.sty
Package: l3box 2012/03/04 v3490 L3 Experimental boxes
\l_tmpb_box=\box26
\l_box_top_dim=\dimen109
\l_box_bottom_dim=\dimen110
\l_box_left_dim=\dimen111
\l_box_right_dim=\dimen112
\l_box_top_new_dim=\dimen113
\l_box_bottom_new_dim=\dimen114
\l_box_left_new_dim=\dimen115
\l_box_right_new_dim=\dimen116
\l_box_internal_box=\box27
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3coffins.sty
Package: l3coffins 2012/03/03 v3482 L3 Experimental coffin code layer
\l_coffin_internal_box=\box28
\l_coffin_internal_dim=\dimen117
\l_coffin_offset_x_dim=\dimen118
\l_coffin_offset_y_dim=\dimen119
\l_coffin_x_dim=\dimen120
\l_coffin_y_dim=\dimen121
\l_coffin_x_prime_dim=\dimen122
\l_coffin_y_prime_dim=\dimen123
\l_coffin_Depth_dim=\dimen124
\l_coffin_Height_dim=\dimen125
\l_coffin_TotalHeight_dim=\dimen126
\l_coffin_Width_dim=\dimen127
\c_empty_coffin=\box29
\l_coffin_aligned_coffin=\box30
\l_coffin_aligned_internal_coffin=\box31
\l_coffin_bounding_shift_dim=\dimen128
\l_coffin_left_corner_dim=\dimen129
\l_coffin_right_corner_dim=\dimen130
\l_coffin_bottom_corner_dim=\dimen131
\l_coffin_top_corner_dim=\dimen132
\l_coffin_scaled_total_height_dim=\dimen133
\l_coffin_scaled_width_dim=\dimen134
\l_coffin_display_coffin=\box32
\l_coffin_display_coord_coffin=\box33
\l_coffin_display_pole_coffin=\box34
\l_coffin_display_offset_dim=\dimen135
\l_coffin_display_x_dim=\dimen136
\l_coffin_display_y_dim=\dimen137
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3color.sty
Package: l3color 2011/09/07 v2776 L3 Experimental colour support
)
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/l3luatex.sty
Package: l3luatex 2012/02/09 v3355 L3 Experimental LuaTeX-specific functions
\g_cctab_allocate_int=\count156
\g_cctab_stack_int=\count157
))
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
Package: xparse 2012/04/23 v3570 L3 Experimental document command parser
\l_xparse_current_arg_int=\count158
\l_xparse_m_args_int=\count159
\l_xparse_mandatory_args_int=\count160
\l_xparse_processor_int=\count161
\l_xparse_v_nesting_int=\count162
)
Package: mmacells 2015/03/05 v0.1.0 Mathematica front end cells

(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
Package: amsmath 2000/07/18 v2.13 AMS math features
\@mathmargin=\skip49

For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
Package: amstext 2000/06/29 v2.01

(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty
File: amsgen.sty 1999/11/30 v2.0
\@emptytoks=\toks14
\ex@=\dimen138
))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty
Package: amsbsy 1999/11/29 v1.2d
\pmbraise@=\dimen139
)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty
Package: amsopn 1999/12/14 v2.01 operator names
)
\inf@bad=\count163
LaTeX Info: Redefining \frac on input line 211.
\uproot@=\count164
\leftroot@=\count165
LaTeX Info: Redefining \overline on input line 307.
\classnum@=\count166
\DOTSCASE@=\count167
LaTeX Info: Redefining \ldots on input line 379.
LaTeX Info: Redefining \dots on input line 382.
LaTeX Info: Redefining \cdots on input line 467.
\Mathstrutbox@=\box35
\strutbox@=\box36
\big@size=\dimen140
LaTeX Font Info:    Redeclaring font encoding OML on input line 567.
LaTeX Font Info:    Redeclaring font encoding OMS on input line 568.
\macc@depth=\count168
\c@MaxMatrixCols=\count169
\dotsspace@=\muskip10
\c@parentequation=\count170
\dspbrk@lvl=\count171
\tag@help=\toks15
\row@=\count172
\column@=\count173
\maxfields@=\count174
\andhelp@=\toks16
\eqnshift@=\dimen141
\alignsep@=\dimen142
\tagshift@=\dimen143
\tagwidth@=\dimen144
\totwidth@=\dimen145
\lineht@=\dimen146
\@envbody=\toks17
\multlinegap=\skip50
\multlinetaggap=\skip51
\mathdisplay@stack=\toks18
LaTeX Info: Redefining [ on input line 2666.
LaTeX Info: Redefining ] on input line 2667.
)
(/usr/share/texlive/texmf-dist/tex/latex/bbm-macros/bbm.sty
Package: bbm 1999/03/15 V 1.2 provides fonts for set symbols - TH
LaTeX Font Info:    Overwriting math alphabet `\mathbbm' in version`bold'
(Font)                  U/bbm/m/n --> U/bbm/bx/n on input line 33.
LaTeX Font Info:    Overwriting math alphabet `\mathbbmss' in version`bold'
(Font)                  U/bbmss/m/n --> U/bbmss/bx/n on input line 35.
)
(/usr/share/texmf/tex/latex/xcolor/xcolor.sty
Package: xcolor 2007/01/21 v2.11 LaTeX color extensions (UK)

(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg
File: color.cfg 2007/01/18 v1.5 color configuration of teTeX/TeXLive
)
Package xcolor Info: Driver file: pdftex.def on input line 225.
LaTeX Info: Redefining \color on input line 702.
Package xcolor Info: Model `cmy' substituted by`cmy0' on input line 1337.
Package xcolor Info: Model `hsb' substituted by`rgb' on input line 1341.
Package xcolor Info: Model `RGB' extended on input line 1353.
Package xcolor Info: Model`HTML' substituted by `rgb' on input line 1355.
Package xcolor Info: Model`Hsb' substituted by `hsb' on input line 1356.
Package xcolor Info: Model`tHsb' substituted by `hsb' on input line 1357.
Package xcolor Info: Model`HSB' substituted by `hsb' on input line 1358.
Package xcolor Info: Model`Gray' substituted by `gray' on input line 1359.
Package xcolor Info: Model`wave' substituted by `hsb' on input line 1360.
)
(/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Package: fancyvrb 2008/02/07

Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz) (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 1999/03/16 v1.13 key=value parser (DPC)
\KV@toks@=\toks19
)
\FV@CodeLineNo=\count175
\FV@InFile=\read1
\FV@TabBox=\box37
\c@FancyVerbLine=\count176
\FV@StepNumber=\count177
\FV@OutFile=\write3
) (/usr/share/texlive/texmf-dist/tex/latex/listings/listings.sty
\lst@mode=\count178
\lst@gtempboxa=\box38
\lst@token=\toks20
\lst@length=\count179
\lst@currlwidth=\dimen147
\lst@column=\count180
\lst@pos=\count181
\lst@lostspace=\dimen148
\lst@width=\dimen149
\lst@newlines=\count182
\lst@lineno=\count183
\lst@maxwidth=\dimen150

(/usr/share/texlive/texmf-dist/tex/latex/listings/lstmisc.sty
File: lstmisc.sty 2007/02/22 1.4 (Carsten Heinz)
\c@lstnumber=\count184
\lst@skipnumbers=\count185
\lst@framebox=\box39
)
(/usr/share/texlive/texmf-dist/tex/latex/listings/listings.cfg
File: listings.cfg 2007/02/22 1.4 listings configuration
))
Package: listings 2007/02/22 1.4 (Carsten Heinz)

(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
Package: graphicx 1999/02/16 v1.0f Enhanced LaTeX Graphics (DPC,SPQR)
\Gin@req@height=\dimen151
\Gin@req@width=\dimen152
)
(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
Package: hyperref 2012/05/13 v6.82q Hypertext links for LaTeX

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
Package: hobsub-hyperref 2012/05/28 v1.13 Bundle oberdiek, subset hyperref (HO)

(/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty
Package: hobsub-generic 2012/05/28 v1.13 Bundle oberdiek, subset generic (HO)
Package: hobsub 2012/05/28 v1.13 Construct package bundles (HO)
Package hobsub Info: Skipping package `infwarerr' (already loaded).
Package hobsub Info: Skipping package`ltxcmds' (already loaded).
Package: ifluatex 2010/03/01 v1.3 Provides the ifluatex switch (HO)
Package ifluatex Info: LuaTeX not detected.
Package: ifvtex 2010/03/01 v1.5 Detect VTeX and its facilities (HO)
Package ifvtex Info: VTeX not detected.
Package: intcalc 2007/09/27 v1.1 Expandable calculations with integers (HO)
Package: ifpdf 2011/01/30 v2.3 Provides the ifpdf switch (HO)
Package ifpdf Info: pdfTeX in PDF mode is detected.
Package: etexcmds 2011/02/16 v1.5 Avoid name clashes with e-TeX commands (HO)
Package etexcmds Info: Could not find \expanded.
(etexcmds)             That can mean that you are not using pdfTeX 1.50 or
(etexcmds)             that some package has redefined \expanded.
(etexcmds)             In the latter case, load this package earlier.
Package: kvsetkeys 2012/04/25 v1.16 Key value parser (HO)
Package: kvdefinekeys 2011/04/07 v1.3 Define keys (HO)
Package: pdftexcmds 2011/11/29 v0.20 Utility functions of pdfTeX for LuaTeX (HO
)
Package pdftexcmds Info: LuaTeX not detected.
Package pdftexcmds Info: \pdf@primitive is available.
Package pdftexcmds Info: \pdf@ifprimitive is available.
Package pdftexcmds Info: \pdfdraftmode found.
Package: pdfescape 2011/11/25 v1.13 Implements pdfTeX's escape features (HO)
Package: bigintcalc 2012/04/08 v1.3 Expandable calculations on big integers (HO
)
Package: bitset 2011/01/30 v1.1 Handle bit-vector datatype (HO)
Package: uniquecounter 2011/01/30 v1.2 Provide unlimited unique counter (HO)
)
Package hobsub Info: Skipping package `hobsub' (already loaded).
Package: letltxmacro 2010/09/02 v1.4 Let assignment for LaTeX macros (HO)
Package: hopatch 2012/05/28 v1.2 Wrapper for package hooks (HO)
Package: xcolor-patch 2011/01/30 xcolor patch
Package: atveryend 2011/06/30 v1.8 Hooks at the very end of document (HO)
Package atveryend Info: \enddocument detected (standard20110627).
Package: atbegshi 2011/10/05 v1.16 At begin shipout hook (HO)
Package: refcount 2011/10/16 v3.4 Data extraction from label references (HO)
Package: hycolor 2011/01/30 v1.7 Color options for hyperref/bookmark (HO)
)
(/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty
Package: ifxetex 2010/09/12 v0.6 Provides ifxetex conditional
)
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
Package: kvoptions 2011/06/30 v3.11 Key value format for package options (HO)
)
\@linkdim=\dimen153
\Hy@linkcounter=\count186
\Hy@pagecounter=\count187

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def
File: pd1enc.def 2012/05/13 v6.82q Hyperref: PDFDocEncoding definition (HO)
)
\Hy@SavedSpaceFactor=\count188

(/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg
File: hyperref.cfg 2002/06/06 v1.2 hyperref configuration of TeXLive
)
Package hyperref Info: Hyper figures OFF on input line 4062.
Package hyperref Info: Link nesting OFF on input line 4067.
Package hyperref Info: Hyper index ON on input line 4070.
Package hyperref Info: Plain pages OFF on input line 4077.
Package hyperref Info: Backreferencing OFF on input line 4082.
Package hyperref Info: Implicit mode ON; LaTeX internals redefined.
Package hyperref Info: Bookmarks ON on input line 4300.
\c@Hy@tempcnt=\count189

(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty
\Urlmuskip=\muskip11
Package: url 2006/04/12  ver 3.3  Verb mode for urls, etc.
)
LaTeX Info: Redefining \url on input line 4653.
\Fld@menulength=\count190
\Field@Width=\dimen154
\Fld@charsize=\dimen155
Package hyperref Info: Hyper figures OFF on input line 5773.
Package hyperref Info: Link nesting OFF on input line 5778.
Package hyperref Info: Hyper index ON on input line 5781.
Package hyperref Info: backreferencing OFF on input line 5788.
Package hyperref Info: Link coloring OFF on input line 5793.
Package hyperref Info: Link coloring with OCG OFF on input line 5798.
Package hyperref Info: PDF/A mode OFF on input line 5803.
LaTeX Info: Redefining \ref on input line 5843.
LaTeX Info: Redefining \pageref on input line 5847.
\Hy@abspage=\count191
\c@Item=\count192
\c@Hfootnote=\count193
)

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
File: hpdftex.def 2012/05/13 v6.82q Hyperref driver for pdfTeX
\Fld@listcount=\count194
\c@bookmark@seq@number=\count195

(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty
Package: rerunfilecheck 2011/04/15 v1.7 Rerun checks for auxiliary files (HO)
Package uniquecounter Info: New unique counter `rerunfilecheck' on input line 2
82.
)
\Hy@SectionHShift=\skip52
)
.................................................
. LaTeX info: "xparse/define-environment"
. 
. Defining document environment 'mmaCell' with arg. spec. 'O{}m' on line 28.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining document command \mmaCellGraphics with arg. spec. 'O{}mm' on line
. 31.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining document command \mmaSet with arg. spec. 'm' on line 34.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining document command \mmaCellIndex with arg. spec. '' on line 37.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining document command \mmaCellForm with arg. spec. 's' on line 44.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining document command \mmaGraphics with arg. spec. 'O{}m' on line 47.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining document command \mmaDefineAnnotation with arg. spec. 'om' on line
. 62.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining document command \mmaDefineFrontEndInStyle with arg. spec.
. 'O{MathematicaFrontEndIn}m' on line 70.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining document command \mmaDefineCellStyle with arg. spec. 'mm' on line
. 73.
.................................................
.................................................
. LaTeX info: "xparse/define-command"
. 
. Defining document command \mmaDefineMathReplacement with arg. spec.
. 'ommO{1}' on line 80.
.................................................
\g_mmacells_index_int=\count196
\g_mmacells_next_emph_class_int=\count197
\l_mmacells_label_box=\box40
\l_mmacells_leftmargin_dim=\dimen156
\l_mmacells_label_dim=\dimen157
\l_mmacells_label_sep_dim=\dimen158
\l_mmacells_x_offset_dim=\dimen159
\l_mmacells_y_offset_dim=\dimen160

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "keys/property-unknown"
! 
! The key property '.initial:n' is unknown.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  

l.344   }

? 
! Emergency stop.
!...............................................  

l.344   }

|'''''''''''''''''''''''''''''''''''''''''''''''
| This is a coding error.
| 
| LaTeX has been asked to set the property '.initial:n' for key
| 'mmacells/verbatimenv': this property is not defined.
|...............................................

Here is how much of TeX's memory you used:
 11797 strings out of 493481
 189617 string characters out of 3143393
 268225 words of memory out of 3000000
 15008 multiletter control sequences out of 15000+200000
 3640 words of font info for 14 fonts, out of 3000000 for 9000
 965 hyphenation exceptions out of 8191
 36i,0n,37p,224b,219s stack positions out of 5000i,500n,10000p,200000b,50000s
!  ==> Fatal error occurred, no output PDF file produced!

**Comment by jkuczm** [comment]
You have old TeX Live distribution from 2012 which includes `l3keys` package version from 2012/03/03, it doesn't support some of features needed by `mmacells` package.

First thing I'd suggest is to upgrade your TeX Live distribution using package manager of your operating system. I don't have Debian based system, but as I can see there's stable version of package with TeX live 2014.

**Comment by wtchan** [comment]
Yep, now it works! Awesome, thanks!

**Comment by wtchan** [comment]
Yep, now it works! Awesome, thanks!

**Comment by vsht** [comment]
I had exactly the same problem when submitting a preprint to [arXiv.org](https://arxiv.org/), where the submission system uses TeXLive 2011. Obviously, you cannot simply tell them to upgrade to a newer version. So I just added all the files from `/usr/share/texlive/texmf-dist/tex/latex/l3kernel` and `/usr/share/texlive/texmf-dist/tex/latex/listings` (I'm on Fedora 23 with TeXLive 2013) to my submission and it worked. Hope this helps to someone facing the same issues.
