### ISSUE TITLE
Automatic line break

### ISSUE THREAD

**Issue by rgugliel** [jkuczm/mmacells#22]
Hi,
Is there a way to get automatic line break?
(the same as the "breaklines=true" option of the lstlisting package)

Thanks!

Best,

Rafael

**Comment by jkuczm** [comment]
`mmacells` uses `listings` under the hood, so you can use all features of `listings`, as long as they work in `listings` - `fancyvrb` interface.

To pass options to `listings` inside `mmaCell` you can use `lst`, or `morelst` key. `lst` will get rid of all previously set `listings` options (including `mmacells` built-in options), `morelst` will add given options to existing ones.

``` tex
\documentclass{article}
\usepackage{mmacells}
\begin{document}

\begin{mmaCell}[morelst={breaklines=true}]{Input}
this is a very long line this is a very long line this is a very long line this is a very long line this is a very long line this is a very long line
\end{mmaCell}

\end{document}
```

![result](https://cloud.githubusercontent.com/assets/4525409/15447165/3c0086a8-1f38-11e6-90dd-16240d860865.png)

**Comment by rgugliel** [comment]
Thanks!
