### ISSUE TITLE
Using prefix form of expressions without extra spaces (e.g. N@f[x])

### ISSUE THREAD

**Issue by Anton-Sakovich** [jkuczm/mmacells#28]
Greetings, jkuczm. First of all, I want to thank you for your _CellToTeX_-_SyntaxAnnotations_-_mmaCells_  bundle.

I have the following issue: if I have several "keywords"  connected by "@" symbol without spaces, then the whole structure is coloured with blue.

If I understand the situation correctly, listings interprets the whole structure as a whole keyword because "@" is a letter by listings' defaults, but maybe I am wrong. I tried to change the role of "@" symbol to "other" and it seemed to work correctly...

**Comment by jkuczm** [comment]
Thanks for reporting it.

You're absolutely right, `@` should be an "other" character.
