### ISSUE TITLE
Polyglossia monofont error

### ISSUE THREAD

**Issue by Anton-Sakovich** [jkuczm/mmacells#30]
Greetings again, jkuczm.

The issue is the following. Let us consider Xe(La)TeX + _polyglossia_ bundle for non-english (russian in my case) document preparation.

There is a well-known issue with _polyglossia_ package that an error

```
! Package polyglossia Error: The current roman font does not contain the Cyrill
ic script!
(polyglossia)                Please define \cyrillicfont with \newfontfamily.

See the polyglossia package documentation for explanation.
```

arises while using some verbatim environments like _Verbatim_ one provided by _fancyvrb_ package, which is used by _mmacells_. One can find a solution (see e.g. [http://tex.stackexchange.com/questions/91507/liberation-mono-the-current-roman-font-does-not-contain-the-cyrillic-script](url) on tex.stackexchange.com) for this problem to add a string
`\newfontfamily\cyrillicfonttt{lmmonolt10-bold.otf}`
in a document.

The point is that, while this string helps in case of _Verbatim_ environment and, furthermore,  there is no any problem with _lstlisting_ environment, even without this "help-string", _mmaCell_ environment still leads to above mentioned error. I.e. this  "help-string" doesn't help in the case of _mmaCell_ environment.

For clarity:

```
\documentclass[a4paper,10pt]{article}

\usepackage[quiet]{fontspec}
\usepackage{polyglossia}
\usepackage{unicode-math}
\usepackage{mmacells}

\setmainfont[Ligatures=NoCommon]{Times New Roman}
\setmathfont{xits-math.otf}
\setmainlanguage{russian}
\setotherlanguage{english}
%\newfontfamily\cyrillicfonttt{lmmonolt10-bold.otf}


\begin{document}

Русский текст.

\begin{Verbatim}
  f[x]
\end{Verbatim}

\end{document}
```

leads to error, while

```
\documentclass[a4paper,10pt]{article}

\usepackage[quiet]{fontspec}
\usepackage{polyglossia}
\usepackage{unicode-math}
\usepackage{mmacells}

\setmainfont[Ligatures=NoCommon]{Times New Roman}
\setmathfont{xits-math.otf}
\setmainlanguage{russian}
\setotherlanguage{english}
\newfontfamily\cyrillicfonttt{lmmonolt10-bold.otf}


\begin{document}

Русский текст.

\begin{Verbatim}
  f[x]
\end{Verbatim}

\end{document}
```

does not. I don't even  need to declare english environment explicitly. 

And this one

```
\documentclass[a4paper,10pt]{article}

\usepackage[quiet]{fontspec}
\usepackage{polyglossia}
\usepackage{unicode-math}
\usepackage{mmacells}

\setmainfont[Ligatures=NoCommon]{Times New Roman}
\setmathfont{xits-math.otf}
\setmainlanguage{russian}
\setotherlanguage{english}
\newfontfamily\cyrillicfonttt{lmmonolt10-bold.otf}


\begin{document}

Русский текст.

\begin{mmaCell}{Input}
  f[x]
\end{mmaCell}

\end{document} 
```

leads to the error anyway.

So, maybe something in _mmacells_ package just doesn't let this trick to work?

P.S.
LaTeX + _fontenc_ + _inputenc_ + _babel_ bundle seems to work fine, i.e.

```
\documentclass[a4paper,10pt]{article}

\usepackage{mmacells}
\usepackage[utf8]{inputenc}
\usepackage[T2A]{fontenc}
\usepackage[english,russian]{babel}

\begin{document}

Русский текст.

\begin{mmaCell}{Input}
  f[x]
\end{mmaCell}

\end{document}
```

works fine. But sometimes it's necessary to use XeTeX...

P.P.S.
Oh, by the way, I omitted _\begin{english}_ and _\end{english}_ because it does not help without help-string present anyway (this is the bug of _polyglossia_) and after explicit redefining there is no need of them. But 

```
\documentclass[a4paper,10pt]{article}

\usepackage[quiet]{fontspec}
\usepackage{polyglossia}
\usepackage{unicode-math}
\usepackage{mmacells}

\setmainfont[Ligatures=NoCommon]{Times New Roman}
\setmathfont{xits-math.otf}
\setmainlanguage{russian}
\setotherlanguage{english}
\newfontfamily\cyrillicfonttt{lmmonolt10-bold.otf}

\begin{document}

Русский текст.

\begin{english}
\begin{mmaCell}{Input}
  f[x]
\end{mmaCell}
\end{english}

\end{document}
```

still doesn't work, while

```
\documentclass[a4paper,10pt]{article}

\usepackage[quiet]{fontspec}
\usepackage{polyglossia}
\usepackage{unicode-math}
\usepackage{mmacells}

\setmainfont[Ligatures=NoCommon]{Times New Roman}
\setmathfont{xits-math.otf}
\setmainlanguage{russian}
\setotherlanguage{english}
\newfontfamily\cyrillicfonttt{lmmonolt10-bold.otf}

\begin{document}

Русский текст.

\begin{english}
\begin{Verbatim}
  f[x]
\end{Verbatim}
\end{english}

\end{document}
```

does.

**Comment by Anton-Sakovich** [comment]
Uph, after a day of fighting against the system, I have understood that I was digging in the wrong way.

The reason was not in the _mmaCells_-_fancyvrb_ interaction, but just in the fact that not only mono type fonts are used but sans serif ones are used too. So,

```
\newfontfamily\cyrillicfonttt{lmmonolt10-regular.otf}
\newfontfamily\cyrillicfontsf{lmsans10-regular.otf}
```

fooled _polyglossia_ and allowed my document to be compiled. So, the problem is not the problem of _mmaCells_ (actually, it is the problem of _fancyvrb_-_polyglossia_ interaction).

The only task left is to find appropriate fonts, but it is another story... I am sorry for the mess I created here.

**Comment by jkuczm** [comment]
This is a problem of interaction between `polyglossia` and specific font you use. It's not related to `mmacells` nor to `fancyvrb`. You don't need `Verbatim` nor `mmaCell` environment to reproduce it, all you need is `\ttfamily` or `\sffamily` somewhere in your document. `Verbatim` (and `mmaCell`) uses the former for code and [`mmaCell`, by default, uses the latter for labels](https://github.com/jkuczm/mmacells/blob/v0.3.1/mmacells.sty#L793).

From `mmacells` side, label formatting can be changed by using `labelstyle` key, either for specific cell: `\begin{mmaCell}[labelstyle=...]{Input}...`, or globally: `\mmaSet{labelstyle=...}`.
