### ISSUE TITLE
mmaInlineCell without a preceding mmaCell doesn't work.

### ISSUE THREAD

**Issue by SPPearce** [jkuczm/mmacells#32]
Hi,

If I try to call \mmaInlineCell before a mmaCell environment I get the following error:
Missing \endcsname inserted.<to be read again>\unhbox ...l: \mmaInlineCell[]{Code}{Module[{a=5}, a]}

Minimal TeX code:

\documentclass[12pt]{article}
\usepackage{mmacells}

\begin{document}
%\begin{mmaCell}[functionlocal=y]{Code}
 % Integrate[y,{y,0,1}]
%\end{mmaCell}

Inline cell: \mmaInlineCell[]{Code}{Module[{a=5}, a]}.

\end{document}

**Comment by jkuczm** [comment]
Thanks for reporting it.

It seems there's a problem with `listings` language initialization, after executing `\FV@FormattingPrep` command from `fancyvrb`.

As a workaround add `{\lstset{language=[base]Mathematica}}` right below  `\usepackage{mmacells}`.

**Comment by jkuczm** [comment]
Should be fixed in [version 0.3.2](https://github.com/jkuczm/mmacells/releases/tag/v0.3.2).

**Comment by SPPearce** [comment]
Thanks, that fixed it, I'll check the new build.
Nice package.
