### ISSUE TITLE
Some Mathematica built-ins are "known" (black) but not all.

### ISSUE THREAD

**Issue by SPPearce** [jkuczm/mmacells#34]
Currently some Mathematica commands are known, such as Sin, Cos, Exp etc. These will therefore show as black, as in Mathematica. However, it only seems to be a subset of the possible commands, as slightly more obscure functions such as PolarPlot are not included. 

I don't see where the already known commands are defined, in order to be able to add more. 
I can add them to each individual mmacells call as defined=..., but a way to specify them upfront would be good.

**Comment by jkuczm** [comment]
`mmacells` uses *Mathematica* keywords provided by [`listings` package](http://ctan.org/pkg/listings). As can be seen on page 62 of [Lan­guage “drivers” de­tails](http://mirrors.ctan.org/macros/latex/contrib/listings/lstdrvrs.pdf), newest keywords come from *Mathematica* version 5.2.

On the level of `mmacells` you can globally add `defined` symbols using `moredefined` key in `\mmaSet`. For example:
``` tex
\mmaSet{moredefined={Authentication,CloudDeploy,PolarPlot}}
```
will globally add `Authentication`, `CloudDeploy`, and `PolarPlot` to list of defined symbols.

**Comment by SPPearce** [comment]
Thank you, that makes sense. Although it doesn't have Clear, which was introduced in version 1. I've emailed a list of updated keywords to the listings package maintainer, and will add them globally as you've shown how to do.
