### ISSUE TITLE
Error: Undefined control sequence (MiKTeX 21.6 Windows)

### ISSUE THREAD

**Issue by johinoli** [jkuczm/mmacells#49]
Hey,

today I tried to use `mmacells` on a fresh windows with new MiKTeX. Unfortunately, I get an error message when compiling the following minimal example:

> \documentclass{article}
> \usepackage{mmacells}
> \begin{document}
> 
> \begin{mmaCell}{Input}
> \mmaSub{x}{1} == \mmaFrac{-\mmaUnd{\(\pmb{\beta}\)} \(\pmb{\pm}\) \mmaSqrt{\mmaSup{\mmaUnd{\(\pmb{\beta}\)}}{2} - 4 \mmaUnd{\(\pmb{\alpha}\)} \mmaUnd{\(\pmb{\gamma}\)}}}{2 \mmaUnd{\(\pmb{\alpha}\)}}
> \end{mmaCell}
> 
> \end{document}

The error message is: 

> ! Undefined control sequence.
> <argument> ...otalleftmargin \hbox_unpack_clear:N 
>                                                   \@labels 
> l.5 \begin{mmaCell}{Input}

I attached the [log file](https://github.com/jkuczm/mmacells/files/7146385/test.log) for more information. 

Best, johinoli

**Comment by jkuczm** [comment]
This should be fixed by #42, which is already merged, but not released yet. Newest [mmacells.sty file from master branch](https://raw.githubusercontent.com/jkuczm/mmacells/master/mmacells.sty) should work without this error.

**Comment by johinoli** [comment]
Works like a charm. Thank you!
